---
- name: Get current Flow Microsegmentation state
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/services/microseg/status"
    method: GET
    validate_certs: "{{ role_nutanix_pc_svc_flow_microseg_host_validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_pc_svc_flow_microseg_state

- name: Debug role_nutanix_pc_svc_flow_microseg_state
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_flow_microseg_state
  when:
    - role_nutanix_pc_svc_flow_microseg_debug

- name: Current status of Flow Microsegmentation service(s)
  ansible.builtin.debug:
    msg: "Flow Microsegmentation is currently in a '{{ role_nutanix_pc_svc_flow_microseg_state.json.service_enablement_status | lower }}' state."
